baseURL = 'https://emilabraham.com/'
languageCode = 'en-us'
title = "Emil's personal site"
theme = 'emil'
[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Thoughts'
  pageRef = '/thoughts'
  weight = 20
